format = """
[╭─](fg:surface2)$directory$git_branch$fill$dotnet$cmd_duration
[╰─$character](fg:surface2)"""

palette = 'catppuccin_mocha'
add_newline = true

[palettes.catppuccin_mocha]
foreground = '#cdd6f4'
background = '#1e1e2e'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
overlay0 = '#6c7086'
text = '#cdd6f4'
blue = '#89b4fa'
cyan = '#89dceb'
green = '#a6e3a1'
orange = '#fab387'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
yellow = '#f9e2af'

[directory]
format = '[󰷏 $read_only$truncation_symbol$path](fg:pink) '
home_symbol = '~'
truncation_symbol = '…/'
truncation_length = 2
read_only = '󱧵 '
read_only_style = 'fg:red'

[git_branch]
format = '[ $symbol$branch](fg:green) '
symbol = ' '

[dotnet]
format = '[](fg:surface2)[ $symbol$tfm](fg:mauve) '
symbol = '󰪮 '

[fill]
symbol = '─'
style = 'fg:surface1'

[cmd_duration]
min_time = 500
format = '[](fg:surface2)[ $duration](fg:orange) '

[character]
success_symbol = '[❯](fg:green)'
error_symbol = '[❯](fg:red)'
