update_check = false
sync_address = "https://atuin.greedo.net"
auto_sync = true
sync_frequency = "1h"

[history]
filter_mode_shell_up_arrow = "directory"

[ui]
style = "compact"
inline_height = 20
show_preview = true
enter_accept = true
